"use client";

import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { useEffect } from "react";
import SignalRService from "./signalRService";
import styles from "./layout.module.css";
import { useRouter } from "next/navigation";
import { ColorModeScript, Divider, Text } from "@chakra-ui/react";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const signalRService = new SignalRService(
      "http://localhost:5142/torrents/hub"
    );
    signalRService.startConnection();

    return () => {
      signalRService.stopConnection();
    };
  }, []);

  // const { colorMode, toggleColorMode } = useColorMode();

  return (
    <html lang="en" style={{ height: "100%", margin: 0 }}>
      <body
        style={{
          height: "100%",
          margin: 0,
          display: "flex",
          flexDirection: "column",
        }}
      >
        <ColorModeScript initialColorMode={"system"} />
        <Providers>
          <div className={styles.root}>
            <SideBar />
            <div className={styles.divider}>
              <Divider orientation="vertical" />
            </div>
            <div id="main" className={styles.main}>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}

function SideBar() {

  return (
    <div id="sidebar" className={styles.sidebar}>
      <SideBarItem label="Torrents" linksTo="/" />
      <SideBarItem label="Peers" linksTo="/" />
      <SideBarItem label="Integrations" linksTo="/" />
      <SideBarItem label="Settings" linksTo="/settings" />
    </div>
  );
}

interface SideBarItemProps {
  label: string;
  linksTo: string;
}

function SideBarItem({ label, linksTo }: SideBarItemProps) {
  const router = useRouter();

  return (
    <div className={styles.sidebarItem} onClick={() => router.push(linksTo)}>
      <Text fontSize={"md"}>{label}</Text>
    </div>
  );
}
