// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torrential;

#nullable disable

namespace Torrential.Migrations
{
    [DbContext(typeof(TorrentialDb))]
    partial class TorrentialDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Torrential.Models.IndexerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("Torrential.TorrentConfiguration", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateFirstSeeded")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DesiredSeedTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InfoHash");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("Torrential.TorrentialSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("ConnectionSettings", "Torrential.TorrentialSettings.ConnectionSettings#ConnectionSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("MaxConnectionsGlobal")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxConnectionsPerTorrent")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxHalfOpenConnections")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FileSettings", "Torrential.TorrentialSettings.FileSettings#FileSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CompletedPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DownloadPath")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SeedSettings", "Torrential.TorrentialSettings.SeedSettings#SeedSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DesiredSeedTimeDays")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TcpListenerSettings", "Torrential.TorrentialSettings.TcpListenerSettings#TcpListenerSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Port")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
