// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torrential.Application.Persistence;

#nullable disable

namespace Torrential.Application.Persistence.Migrations
{
    [DbContext(typeof(TorrentDbContext))]
    [Migration("20260215191421_AddSettings")]
    partial class AddSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Torrential.Application.Persistence.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHalfOpenConnections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPeersPerTorrent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Torrential.Application.Persistence.TorrentEntity", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnounceUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPieces")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PieceHashes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("PieceSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedFileIndicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfoHash");

                    b.ToTable("Torrents");
                });
#pragma warning restore 612, 618
        }
    }
}
